// Since last run: what a version changed against its parent, in figures the
// ledger holds and in plain words. Nothing here is generated by a model; every
// line is read off the two records.
import { store } from './store.js';

const spent = (x) => Math.round(((x.settlement?.settled ?? x.spent) || 0) * 10) / 10;
const words = (h) => (h ? h.replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>|<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length : null);
const key = (s) => s.url || s.title;
const name = (s) => s.title || s.url;
const list = (xs) => xs.slice(0, 4).join(', ') + (xs.length > 4 ? ` and ${xs.length - 4} more` : '');

export function missionDelta(m) {
  if (!m?.lineage?.parentId) return null;
  const p = store.mission(m.lineage.parentId);
  if (!p) return null;
  const done = ['FILLED', 'KILLED'].includes(m.status);
  const ps = p.sources || [], ms = m.sources || [];
  const pk = new Set(ps.map(key)), mk = new Set(ms.map(key));
  const added = ms.filter((s) => !pk.has(key(s))).map(name), dropped = ps.filter((s) => !mk.has(key(s))).map(name);
  const gate = (x) => (x.gateResult ? { cleared: !!x.gateResult.cleared, failed: (x.gateResult.failed || []).length, patches: (x.patches || []).length } : null);
  const g = { parent: gate(p), now: gate(m) };
  const w = { parent: words(p.artifactId ? store.artifactHtml(p.artifactId) : null), now: words(m.artifactId ? store.artifactHtml(m.artifactId) : null) };
  const del = (x) => [...new Set((x.deliveries || []).filter((d) => d.ok).map((d) => d.connector))];
  const d = { parent: del(p), now: del(m) };
  const cost = { parent: spent(p), now: spent(m) };
  const lines = [];
  if (done) {
    const diff = Math.round((cost.now - cost.parent) * 10) / 10;
    lines.push(`Settled ${cost.now} cr against ${cost.parent} cr last time${diff === 0 ? ', the same' : diff > 0 ? `, ${diff} cr more` : `, ${-diff} cr less`}.`);
    if (g.now && g.parent) lines.push(g.now.patches === 0 && g.parent.patches === 0 ? 'Cleared the gate first time, as before.' : `Gate took ${g.now.patches} patch${g.now.patches === 1 ? '' : 'es'} this time, ${g.parent.patches} last time.`);
    else if (g.now) lines.push(g.now.patches === 0 ? 'Cleared the gate first time.' : `Gate took ${g.now.patches} patch${g.now.patches === 1 ? '' : 'es'}.`);
  }
  if (added.length || dropped.length) lines.push(`${added.length ? `${added.length} new source${added.length === 1 ? '' : 's'}: ${list(added)}` : 'No new sources'}${dropped.length ? `; ${dropped.length} dropped: ${list(dropped)}` : ''}.`);
  else if (ms.length) lines.push(`Same ${ms.length} source${ms.length === 1 ? '' : 's'} as last time.`);
  if (m.dissent?.model && !p.dissent?.model) lines.push(`Dissent carried from ${m.dissent.model}; none last time.`);
  else if (!m.dissent?.model && p.dissent?.model) lines.push(`No dissent this time; ${p.dissent.model} dissented last time.`);
  else if (m.dissent?.model) lines.push(`Dissent carried from ${m.dissent.model}, as last time.`);
  if (w.now != null && w.parent != null) { const dw = w.now - w.parent; lines.push(`Artifact runs ${w.now} words, ${dw === 0 ? 'the same length' : dw > 0 ? `${dw} more than last time` : `${-dw} fewer than last time`}.`); }
  if (done && (d.now.length || d.parent.length)) lines.push(d.now.length ? `Delivered to ${d.now.join(', ')}${d.now.join() === d.parent.join() ? ', as before' : d.parent.length ? ` (last time: ${d.parent.join(', ')})` : ''}.` : `Delivered nowhere this time; last time to ${d.parent.join(', ')}.`);
  if (m.lineage.feedback?.length) lines.push(`Notes that drove this version: ${m.lineage.feedback.map((f) => `"${f}"`).join(', ')}.`);
  return {
    parent: { id: p.id, serial: p.serial, version: p.lineage?.version || 1, artifactId: p.artifactId || null },
    version: m.lineage.version, reason: m.standingOrderId ? 'standing order' : 'amendment', done,
    cost, gate: g, sources: { added, dropped, count: ms.length, parentCount: ps.length }, dissent: { parent: p.dissent?.model || null, now: m.dissent?.model || null }, words: w, deliveries: d,
    lines,
  };
}
