// The app leaves the house as a native project. The working app on the page
// is a web app: it runs full screen on a phone and can be added to a home
// screen, and it cannot go to a store. This packs the same app, the same
// screens, lists, search, add, edit, done, delete and settings, kept on the
// device, as an Expo project: unzip, npm install, npx expo start, and it runs
// on a real phone in Expo Go; eas build takes it to the stores. The project
// is built from the page the house keeps, so a page edited since still packs
// the way it reads, and it carries the icon drawn on the owner's key.
import zlib from 'node:zlib';
import { zipStore } from './export.js';

// A PNG in code, so the project has an icon even when no key drew one: a
// rounded square in the house green with a paler disc, 512 by 512.
export function houseIconPng(size = 512, rgb = [29, 92, 58]) {
  const W = size, H = size, raw = Buffer.alloc((W * 4 + 1) * H);
  const radius = size * 0.22;
  for (let y = 0; y < H; y++) {
    raw[y * (W * 4 + 1)] = 0;
    for (let x = 0; x < W; x++) {
      const i = y * (W * 4 + 1) + 1 + x * 4;
      const dx = Math.max(0, Math.abs(x - (W - 1) / 2) - ((W - 1) / 2 - radius)), dy = Math.max(0, Math.abs(y - (H - 1) / 2) - ((H - 1) / 2 - radius));
      const inside = Math.hypot(dx, dy) <= radius;
      const disc = Math.hypot(x - W * 0.5, y - H * 0.5) <= size * 0.24;
      raw[i] = inside ? (disc ? Math.min(255, rgb[0] + 190) : rgb[0]) : 0;
      raw[i + 1] = inside ? (disc ? Math.min(255, rgb[1] + 150) : rgb[1]) : 0;
      raw[i + 2] = inside ? (disc ? Math.min(255, rgb[2] + 170) : rgb[2]) : 0;
      raw[i + 3] = inside ? 255 : 0;
    }
  }
  const crcTable = []; for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; crcTable.push(c >>> 0); }
  const crc = (buf) => { let c = 0xFFFFFFFF; for (const b of buf) c = crcTable[(c ^ b) & 0xFF] ^ (c >>> 8); return (c ^ 0xFFFFFFFF) >>> 0; };
  const chunk = (type, data) => { const len = Buffer.alloc(4); len.writeUInt32BE(data.length); const td = Buffer.concat([Buffer.from(type), data]); const c = Buffer.alloc(4); c.writeUInt32BE(crc(td)); return Buffer.concat([len, td, c]); };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(W, 0); ihdr.writeUInt32BE(H, 4); ihdr[8] = 8; ihdr[9] = 6;
  return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}

export function appDataFromHtml(html) {
  const m = String(html || '').match(/<script type="application\/json" id="app-data">([\s\S]*?)<\/script>/);
  if (!m) return null;
  try { const d = JSON.parse(m[1]); return d && Array.isArray(d.screens) && d.screens.length ? d : null; } catch { return null; }
}

const slug = (s) => String(s || 'app').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'app';
const ident = (s) => { const w = String(s || 'app').toLowerCase().replace(/[^a-z0-9]+/g, ''); return (w.match(/^[a-z]/) ? w : 'app' + w).slice(0, 30) || 'app'; };

// The whole app, in one file, no navigation library: the tabs are its own.
const APP_JS = String.raw`// Generated by Prajñā. The same app as the delivered page, as a native
// project: screens, lists, search, add, edit, done, delete, settings, kept on
// the device. No navigation library: the tabs are the app's own.
import React, { useEffect, useMemo, useState } from 'react';
import { SafeAreaView, View, Text, TextInput, FlatList, Pressable, StyleSheet, Modal, Alert, StatusBar, useColorScheme, Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import DATA from './app-data.json';

const KEY = 'prajna-app-' + DATA.serial;
const fresh = () => ({
  items: Object.fromEntries(DATA.screens.map((sc) => [sc.id, sc.items.map((it, i) => ({ id: sc.id + '-' + i, title: it.b, note: it.s, done: false, at: Date.now() }))])),
  prefs: { theme: 'system', hideDone: false },
});

export default function App() {
  const [state, setState] = useState(null);
  const [tab, setTab] = useState(DATA.screens[0].id);
  const [q, setQ] = useState('');
  const [sheet, setSheet] = useState(null); // { kind: 'add' | 'edit' | 'settings', item? }
  const system = useColorScheme();
  useEffect(() => { AsyncStorage.getItem(KEY).then((v) => { try { const s = v && JSON.parse(v); setState(s && s.items ? s : fresh()); } catch (e) { setState(fresh()); } }); }, []);
  useEffect(() => { if (state) AsyncStorage.setItem(KEY, JSON.stringify(state)).catch(() => {}); }, [state]);
  const dark = state ? (state.prefs.theme === 'system' ? system === 'dark' : state.prefs.theme === 'dark') : false;
  const c = dark ? { bg: '#0f1512', card: '#182019', ink: '#eef2ec', soft: '#9fb0a5', acc: '#7fbf9a', line: '#26312a' } : { bg: '#f2f4ef', card: '#ffffff', ink: '#101c16', soft: '#5b6960', acc: '#1d5c3a', line: '#dde3dc' };
  const sc = DATA.screens.find((s) => s.id === tab) || DATA.screens[0];
  const items = useMemo(() => {
    if (!state) return [];
    const all = state.items[sc.id] || [];
    const term = q.trim().toLowerCase();
    return all.filter((it) => (!term || (it.title + ' ' + it.note).toLowerCase().includes(term)) && !(state.prefs.hideDone && it.done));
  }, [state, sc.id, q]);
  const update = (fn) => setState((s) => { const n = JSON.parse(JSON.stringify(s)); fn(n); return n; });
  const toggle = (it) => update((n) => { const x = n.items[sc.id].find((y) => y.id === it.id); if (x) x.done = !x.done; });
  const remove = (it) => Alert.alert('Delete ' + sc.noun + '?', it.title, [{ text: 'Keep', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => update((n) => { n.items[sc.id] = n.items[sc.id].filter((y) => y.id !== it.id); }) }]);
  const save = (title, note) => {
    const t = title.trim(); if (!t) return;
    if (sheet && sheet.kind === 'edit') update((n) => { const x = n.items[sc.id].find((y) => y.id === sheet.item.id); if (x) { x.title = t; x.note = note.trim(); } });
    else update((n) => { n.items[sc.id].unshift({ id: sc.id + '-' + Date.now(), title: t, note: note.trim(), done: false, at: Date.now() }); });
    setSheet(null);
  };
  if (!state) return <SafeAreaView style={[st.root, { backgroundColor: c.bg }]} />;
  return (
    <SafeAreaView style={[st.root, { backgroundColor: c.bg }]}>
      <StatusBar barStyle={dark ? 'light-content' : 'dark-content'} />
      <View style={st.top}>
        <Text style={[st.brand, { color: c.ink }]}>{DATA.name}</Text>
        <Pressable onPress={() => setSheet({ kind: 'settings' })} accessibilityLabel="Settings" style={st.gear}><Text style={{ color: c.soft, fontSize: 22 }}>⋯</Text></Pressable>
      </View>
      <Text style={[st.title, { color: c.ink }]}>{sc.title}</Text>
      <Text style={[st.body, { color: c.soft }]}>{sc.body}</Text>
      <TextInput value={q} onChangeText={setQ} placeholder={'Search ' + sc.plural} placeholderTextColor={c.soft} style={[st.search, { backgroundColor: c.card, color: c.ink, borderColor: c.line }]} />
      <FlatList
        data={items}
        keyExtractor={(it) => it.id}
        contentContainerStyle={{ paddingBottom: 120 }}
        ListEmptyComponent={<Text style={[st.empty, { color: c.soft }]}>{q ? 'Nothing matches “' + q + '”.' : 'No ' + sc.plural + ' yet. Add the first one below.'}</Text>}
        renderItem={({ item }) => (
          <Pressable onPress={() => setSheet({ kind: 'edit', item })} onLongPress={() => remove(item)} style={[st.row, { backgroundColor: c.card, borderColor: c.line }]}>
            <Pressable onPress={() => toggle(item)} accessibilityLabel={item.done ? 'Mark not done' : 'Mark done'} style={[st.check, { borderColor: c.acc, backgroundColor: item.done ? c.acc : 'transparent' }]} />
            <View style={{ flex: 1 }}>
              <Text style={[st.rowTitle, { color: c.ink, textDecorationLine: item.done ? 'line-through' : 'none' }]}>{item.title}</Text>
              {item.note ? <Text style={[st.rowNote, { color: c.soft }]}>{item.note}</Text> : null}
            </View>
          </Pressable>
        )}
      />
      <Pressable onPress={() => setSheet({ kind: 'add' })} style={[st.fab, { backgroundColor: c.acc }]}><Text style={st.fabText}>{sc.cta}</Text></Pressable>
      <View style={[st.tabs, { backgroundColor: c.card, borderColor: c.line }]}>
        {DATA.screens.map((s) => (
          <Pressable key={s.id} onPress={() => { setTab(s.id); setQ(''); }} style={st.tab} accessibilityState={{ selected: s.id === tab }}>
            <View style={[st.dot, { backgroundColor: s.id === tab ? c.acc : c.line }]} />
            <Text style={[st.tabText, { color: s.id === tab ? c.acc : c.soft }]}>{s.tab}</Text>
          </Pressable>
        ))}
      </View>
      <Modal visible={!!sheet} transparent animationType="slide" onRequestClose={() => setSheet(null)}>
        <Pressable style={st.scrim} onPress={() => setSheet(null)} />
        <View style={[st.sheet, { backgroundColor: c.card }]}>
          {sheet && sheet.kind === 'settings' ? (
            <Settings c={c} prefs={state.prefs} onChange={(prefs) => update((n) => { n.prefs = prefs; })} onReset={() => { setState(fresh()); setSheet(null); }} onClose={() => setSheet(null)} />
          ) : sheet ? (
            <Editor c={c} noun={sc.noun} item={sheet.kind === 'edit' ? sheet.item : null} onSave={save} onClose={() => setSheet(null)} />
          ) : null}
        </View>
      </Modal>
    </SafeAreaView>
  );
}

function Editor({ c, noun, item, onSave, onClose }) {
  const [title, setTitle] = useState(item ? item.title : '');
  const [note, setNote] = useState(item ? item.note : '');
  return (
    <View>
      <Text style={[st.sheetTitle, { color: c.ink }]}>{item ? 'Edit ' + noun : 'New ' + noun}</Text>
      <TextInput value={title} onChangeText={setTitle} placeholder="Title" placeholderTextColor={c.soft} autoFocus style={[st.input, { color: c.ink, borderColor: c.line }]} />
      <TextInput value={note} onChangeText={setNote} placeholder="One line of context" placeholderTextColor={c.soft} style={[st.input, { color: c.ink, borderColor: c.line }]} />
      <View style={st.actions}>
        <Pressable onPress={onClose} style={[st.btn, { borderColor: c.line }]}><Text style={{ color: c.ink }}>Cancel</Text></Pressable>
        <Pressable onPress={() => onSave(title, note)} style={[st.btn, { backgroundColor: c.acc, borderColor: c.acc }]}><Text style={{ color: '#fff', fontWeight: '700' }}>{item ? 'Save' : 'Add'}</Text></Pressable>
      </View>
    </View>
  );
}

function Settings({ c, prefs, onChange, onReset, onClose }) {
  const themes = ['system', 'light', 'dark'];
  return (
    <View>
      <Text style={[st.sheetTitle, { color: c.ink }]}>Settings</Text>
      <Text style={{ color: c.soft, marginBottom: 6 }}>Theme</Text>
      <View style={st.actions}>
        {themes.map((t) => <Pressable key={t} onPress={() => onChange({ ...prefs, theme: t })} style={[st.btn, { borderColor: prefs.theme === t ? c.acc : c.line }]}><Text style={{ color: c.ink }}>{t}</Text></Pressable>)}
      </View>
      <Pressable onPress={() => onChange({ ...prefs, hideDone: !prefs.hideDone })} style={[st.btn, { borderColor: c.line, marginTop: 10 }]}><Text style={{ color: c.ink }}>{prefs.hideDone ? 'Show done items' : 'Hide done items'}</Text></Pressable>
      <Pressable onPress={() => Alert.alert('Start over?', 'Every list goes back to the way it was delivered.', [{ text: 'Keep', style: 'cancel' }, { text: 'Start over', style: 'destructive', onPress: onReset }])} style={[st.btn, { borderColor: c.line, marginTop: 10 }]}><Text style={{ color: c.ink }}>Start over</Text></Pressable>
      <Pressable onPress={onClose} style={[st.btn, { backgroundColor: c.acc, borderColor: c.acc, marginTop: 16 }]}><Text style={{ color: '#fff', fontWeight: '700' }}>Done</Text></Pressable>
      <Text style={{ color: c.soft, marginTop: 14, fontSize: 12 }}>Data stays on this device. Built by Prajñā, {DATA.serial}.</Text>
    </View>
  );
}

const st = StyleSheet.create({
  root: { flex: 1, paddingTop: Platform.OS === 'android' ? 28 : 0 },
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 8 },
  brand: { fontWeight: '800', fontSize: 15, letterSpacing: 0.3 },
  gear: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 30, fontWeight: '800', letterSpacing: -0.5, paddingHorizontal: 18, marginTop: 4 },
  body: { paddingHorizontal: 18, marginTop: 4, marginBottom: 12, fontSize: 14 },
  search: { marginHorizontal: 18, marginBottom: 10, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 15 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12, marginHorizontal: 18, marginBottom: 8, padding: 14, borderRadius: 14, borderWidth: 1 },
  check: { width: 24, height: 24, borderRadius: 12, borderWidth: 2 },
  rowTitle: { fontSize: 16, fontWeight: '600' },
  rowNote: { fontSize: 13, marginTop: 2 },
  empty: { textAlign: 'center', marginTop: 40, paddingHorizontal: 30 },
  fab: { position: 'absolute', right: 18, bottom: 84, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, minHeight: 48, justifyContent: 'center' },
  fabText: { color: '#fff', fontWeight: '700' },
  tabs: { position: 'absolute', left: 0, right: 0, bottom: 0, flexDirection: 'row', borderTopWidth: 1, paddingBottom: Platform.OS === 'ios' ? 18 : 8, paddingTop: 8 },
  tab: { flex: 1, alignItems: 'center', minHeight: 44, justifyContent: 'center' },
  dot: { width: 8, height: 8, borderRadius: 4, marginBottom: 4 },
  tabText: { fontSize: 12, fontWeight: '600' },
  scrim: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)' },
  sheet: { padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 34 },
  sheetTitle: { fontSize: 18, fontWeight: '800', marginBottom: 12 },
  input: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, fontSize: 15, marginBottom: 10 },
  actions: { flexDirection: 'row', gap: 10, justifyContent: 'flex-end', flexWrap: 'wrap' },
  btn: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 16, paddingVertical: 10, minHeight: 44, justifyContent: 'center' },
});
`;

export function expoFromArtifact({ artifact, mission, html, iconBytes }) {
  const data = appDataFromHtml(html);
  if (!data) return null;
  const name = String(data.name || artifact.title || 'App').slice(0, 40);
  const s = slug(name), id = ident(name);
  const drawn = !!(iconBytes && iconBytes.length > 8 && iconBytes[0] === 0x89 && iconBytes[1] === 0x50);
  const icon = drawn ? iconBytes : houseIconPng();
  const pkg = {
    name: s, version: '1.0.0', private: true, main: 'expo/AppEntry.js',
    scripts: { start: 'expo start', android: 'expo start --android', ios: 'expo start --ios', web: 'expo start --web' },
    dependencies: { expo: '~52.0.0', 'expo-asset': '~11.0.5', 'expo-status-bar': '~2.0.1', react: '18.3.1', 'react-native': '0.76.5', '@react-native-async-storage/async-storage': '1.23.1' },
    devDependencies: { '@babel/core': '^7.25.0' },
  };
  const app = { expo: {
    name, slug: s, version: '1.0.0', orientation: 'portrait', icon: './assets/icon.png', userInterfaceStyle: 'automatic',
    splash: { image: './assets/icon.png', resizeMode: 'contain', backgroundColor: '#f2f4ef' },
    ios: { supportsTablet: false, bundleIdentifier: `com.prajna.${id}` },
    android: { package: `com.prajna.${id}`, adaptiveIcon: { foregroundImage: './assets/icon.png', backgroundColor: '#f2f4ef' } },
    extra: { prajna: { serial: artifact.serial, artifact: artifact.id, version: artifact.version, mission: mission?.id || null } },
  } };
  const readme = [
    `# ${name}`,
    '',
    `A native app packed by Prajñā from delivery ${artifact.serial} (v${artifact.version}). It is the same app as the delivered page: ${data.screens.length} screens (${data.screens.map((x) => x.tab).join(', ')}), lists with search, add, edit, mark done, delete and settings, with the data kept on the device.`,
    '',
    '## Run it on your phone',
    '',
    '1. Install Node 18 or newer, then in this folder: `npm install`',
    '2. `npx expo start`',
    '3. Install Expo Go on your phone and scan the QR code. The app opens on the phone.',
    '',
    '## Build for the stores',
    '',
    '`npx eas build --platform ios` or `--platform android` with an Expo account (see https://docs.expo.dev/build/setup/). Change `bundleIdentifier` and `package` in app.json to your own domain first.',
    '',
    '## What is inside',
    '',
    '- `App.js`: the whole app, no navigation library, the tabs are its own.',
    '- `app-data.json`: the screens, their nouns and their starting items, exactly as delivered.',
    `- \`assets/icon.png\`: ${drawn ? "the icon drawn on the owner's key for this app." : 'a house icon; run the desk with an image key for one drawn for this app.'}`,
    '- `app.json`: the Expo configuration; `extra.prajna` names the delivery this came from.',
    mission?.authored?.live ? `\nThe substance was written by ${mission.authored.model} on the owner's own key.` : '',
    '',
  ].join('\n');
  const when = new Date(artifact.createdAt || Date.now());
  return zipStore([
    { name: `${s}/package.json`, data: JSON.stringify(pkg, null, 2) },
    { name: `${s}/app.json`, data: JSON.stringify(app, null, 2) },
    { name: `${s}/babel.config.js`, data: "module.exports = function (api) { api.cache(true); return { presets: ['babel-preset-expo'] }; };\n" },
    { name: `${s}/App.js`, data: APP_JS },
    { name: `${s}/app-data.json`, data: JSON.stringify({ serial: data.serial, name, screens: data.screens }, null, 2) },
    { name: `${s}/assets/icon.png`, data: icon },
    { name: `${s}/.gitignore`, data: 'node_modules/\n.expo/\ndist/\n' },
    { name: `${s}/README.md`, data: readme },
  ], when);
}
