// The house rules: Terms and Conditions, the Privacy and GDPR Policy, and the
// AI Disclaimer. Served as public pages, shown on the acceptance screen, and
// versioned: a new version asks every workspace to accept again. Plain HTML
// authored here; nothing user-supplied is ever rendered into these pages.
export const LEGAL_VERSION = '2026-09-04';
const OPERATOR = 'the operator of Prajñā (“the Operator”, “we”, “us”)';

const TERMS = `
<h2>1. Who we are and what this is</h2>
<p>Prajñā (“the Service”) is an agent workspace operated by ${OPERATOR}. It turns a request into a contract (a plan and a price in house credits), runs it as a mission, and delivers an artifact with its provenance. These Terms and Conditions (“Terms”) are a binding agreement between you and the Operator. By accepting them, or by using the Service, you agree to them. If you do not agree, do not use the Service.</p>
<h2>2. Eligibility</h2>
<p>You must be at least 18 years old and able to form a binding contract. If you use the Service on behalf of an organisation, you confirm that you are authorised to bind it, and “you” includes that organisation.</p>
<h2>3. Access, the access code and your account</h2>
<p>A workspace may be protected by an access code. You are responsible for keeping the code and any session confidential, for everyone who uses the workspace through it, and for every action taken under it. Tell us at once if you believe it has been compromised. We may suspend or end access at any time if we reasonably believe these Terms have been breached, the Service is being misused, or continuing would expose us or others to harm or liability.</p>
<h2>4. Your content and your keys</h2>
<p>You keep every right you hold in the prompts, attachments, notes and other material you supply (“Inputs”), and in the artifacts the Service delivers to you (“Outputs”), to the extent the law allows rights in machine-generated material. You grant us a worldwide, non-exclusive, royalty-free licence to store, process, transmit and display Inputs and Outputs solely to operate, secure, support and improve the Service. You are solely responsible for your Inputs: that you have the right to supply them, that they are lawful, and that they do not infringe any right of any person.</p>
<p>The Service lets you bring your own API keys for third-party model and search providers (“BYOK”). Keys are held in the Service's memory for the session only and are never written to disk. Calls made with your keys are made on your account with that provider, under that provider's terms and prices, and at your cost. We are not a party to your agreement with any provider and are not responsible for their availability, output, pricing or conduct. You are responsible for keeping your keys valid, funded and confidential, and for revoking them with the provider if you believe they have been exposed.</p>
<h2>5. Acceptable use</h2>
<p>You agree not to use the Service to: break any law or regulation; infringe intellectual property, privacy or other rights; generate, store or distribute material that is unlawful, defamatory, harassing, hateful, sexually explicit involving minors, or that promotes violence or self-harm; create or spread malware, spam or deceptive content; probe, scan, overload, reverse-engineer or interfere with the Service or its infrastructure; scrape the Service or circumvent rate limits or access controls; impersonate any person or misrepresent Outputs as human-authored where that matters; or make decisions with legal, financial, medical, safety or similar consequences on the basis of Outputs without independent professional review. We may remove content and suspend access to enforce this section.</p>
<h2>6. Credits, plans and billing</h2>
<p>Missions are priced in house credits. A ticket states an estimate and a ceiling; stamping a ticket reserves the ceiling; the run settles what it used; the remainder is released. Nothing beyond the ceiling is spent without your decision. Credits have no cash value, are not refundable, cannot be transferred or exchanged, and may expire or be adjusted if we change the Service. Where billing is marked as demonstration billing, no payment is collected and no paid entitlement is created. If and when paid plans are offered, the price, term, renewal and cancellation terms shown at the time of purchase apply in addition to these Terms.</p>
<h2>7. Outputs, provenance and no reliance</h2>
<p>Outputs are generated by software, including third-party AI models you select, and by house templates that are labelled as sample material. The Service records provenance (who wrote what, which sources, what was validated, what you decided) and applies automated checks, but no check guarantees that an Output is accurate, complete, current, lawful, fit for any purpose, or free of third-party rights. Sample material, illustrative figures and placeholders are marked as such and are not statements of fact. You are responsible for reviewing and verifying every Output before relying on it or sharing it. The AI Disclaimer forms part of these Terms.</p>
<h2>8. Third-party services</h2>
<p>The Service connects to third-party services at your direction: model providers, search providers, source sites such as Wikipedia, and apps you connect through OAuth (for example Google, Slack, Notion, GitHub). Your use of those services is governed by their terms and privacy policies. We do not control them and are not liable for them. Tokens for connected apps are held in memory for the session only.</p>
<h2>9. Sharing and public links</h2>
<p>You may publish artifacts, records and showcase entries at public links. Anything you publish is visible to anyone with the link until you revoke it, may be cached or copied by others, and is published under your responsibility. Do not publish material you do not have the right to publish or that contains personal data of others without a lawful basis.</p>
<h2>10. Intellectual property in the Service</h2>
<p>The Service, its software, design, names, marks and content other than your Inputs and Outputs are owned by the Operator or its licensors and are protected by law. Except as expressly allowed by these Terms or a separate written licence, you may not copy, modify, distribute, sell, lease, or create derivative works from the Service.</p>
<h2>11. Disclaimer of warranties</h2>
<p>THE SERVICE AND ALL OUTPUTS ARE PROVIDED “AS IS” AND “AS AVAILABLE”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AVAILABILITY OR THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE OR ERROR-FREE. YOUR USE IS AT YOUR OWN RISK.</p>
<h2>12. Limitation of liability</h2>
<p>TO THE FULLEST EXTENT PERMITTED BY LAW, THE OPERATOR AND ITS AFFILIATES, LICENSORS AND CONTRIBUTORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL OR BUSINESS OPPORTUNITY, ARISING OUT OF OR IN CONNECTION WITH THE SERVICE OR ANY OUTPUT, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, EVEN IF ADVISED OF THE POSSIBILITY. THE OPERATOR'S TOTAL LIABILITY FOR ALL CLAIMS IN ANY TWELVE-MONTH PERIOD WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US FOR THE SERVICE IN THAT PERIOD AND (B) ONE THOUSAND INDIAN RUPEES (INR 1,000). NOTHING IN THESE TERMS EXCLUDES LIABILITY THAT CANNOT BE EXCLUDED BY LAW.</p>
<h2>13. Indemnity</h2>
<p>You will defend, indemnify and hold harmless the Operator and its affiliates, officers and contributors from any claim, loss, liability, cost or expense (including reasonable legal fees) arising from your Inputs, your Outputs, your use of the Service, your use of third-party services through the Service, your publication of any material, or your breach of these Terms or of any law.</p>
<h2>14. Suspension, termination and export</h2>
<p>You may stop using the Service at any time and may export your missions and artifacts from the Settings page. We may suspend or terminate the Service or your access at any time, with or without notice, including for breach, legal risk, security, or discontinuation of the Service. Sections 4, 7 and 9 to 17 survive termination.</p>
<h2>15. Changes</h2>
<p>We may change the Service and these Terms. Material changes to these Terms will be presented for acceptance again in the Service, with a new version date. Continued use after a change means you accept it.</p>
<h2>16. Governing law and disputes</h2>
<p>These Terms are governed by the laws of India, without regard to conflict-of-law rules. The courts at Bengaluru, Karnataka, India have exclusive jurisdiction over any dispute, subject to any right you have under mandatory consumer law of your place of residence. Before starting proceedings, each party will try in good faith to resolve the dispute by written notice and discussion for thirty days.</p>
<h2>17. General</h2>
<p>These Terms, the Privacy and GDPR Policy and the AI Disclaimer are the entire agreement between you and the Operator about the Service. If any provision is unenforceable, the rest remains in force. Our failure to enforce a provision is not a waiver. You may not assign these Terms; we may assign them to a successor. Notices to us go through the support link in Get Help; notices to you go to the email on your profile or through the Service.</p>
`;

const PRIVACY = `
<h2>1. Scope</h2>
<p>This Privacy and GDPR Policy explains what personal data ${OPERATOR} collects when you use Prajñā, why, on what legal basis, for how long, who it is shared with, and your rights. It is written to meet the EU General Data Protection Regulation (GDPR), the UK GDPR, and India's Digital Personal Data Protection Act, 2023 (DPDP). Where those laws use different words (“data subject” and “data principal”, “controller” and “data fiduciary”), this Policy uses the plainer one. The Operator is the controller (data fiduciary) for the data described here.</p>
<h2>2. What we collect</h2>
<ul>
<li><b>Profile</b>: the name, handle, email and bio you choose to enter. None is required to open the house; the greeting stays generic until you give a name.</li>
<li><b>Workspace content</b>: prompts, chat messages, attachments you upload (text files are read; other files are recorded by name only), missions and their tapes, artifacts, notes, comparisons, the credit ledger, showcase submissions, media you generate.</li>
<li><b>Technical data</b>: IP address and request metadata used only for rate limiting and security, held in memory; the session cookie described below; server logs that record events, errors and, where relevant, the address of a request.</li>
<li><b>Keys and tokens</b>: API keys for model or search providers and OAuth tokens for connected apps are held in the Service's memory for the session only. They are never written to disk, never shown back to you unmasked, and disappear when the server restarts or you remove them.</li>
<li><b>Data you send to providers</b>: when you use your own keys or connected apps, your prompts, attachments and related content are sent to that provider to perform the request. Their processing is governed by their policies.</li>
</ul>
<p>We do not use your workspace content to train models. We do not sell personal data. We do not use advertising trackers.</p>
<h2>3. Why and on what basis</h2>
<ul>
<li>To provide the Service you asked for (contract): running missions, storing your workspace, delivering artifacts, keeping the ledger.</li>
<li>To secure and operate the Service (legitimate interest): rate limiting, abuse prevention, error logs, backups.</li>
<li>To send you a digest by email, notifications, or the daily digest through your own Google account (consent, which you can withdraw in Settings at any time).</li>
<li>To comply with law or respond to lawful requests (legal obligation).</li>
</ul>
<h2>4. Cookies and local storage</h2>
<p>The Service sets one cookie, <code>prajna_session</code>, only when an access code is in use; it is an HttpOnly, SameSite=Lax cookie (Secure over TLS) that keeps you signed in for up to 30 days and contains no personal data. The browser's local storage holds your theme, whether you dismissed the welcome, and your notification preference. There are no third-party cookies.</p>
<h2>5. Sharing and processors</h2>
<p>We share personal data only with: hosting and infrastructure providers that run the Service (currently Railway, on servers you can locate through the status page), which process data on our instructions; the third-party providers you choose to connect or key in, who act as independent controllers for what you send them; and authorities where the law requires. Anything you publish at a public link (a shared artifact, record, or showcase entry) is available to anyone with the link until you revoke it.</p>
<h2>6. International transfers</h2>
<p>The Service may be hosted, and the providers you choose may operate, outside your country, including outside the EEA, the UK and India. Where GDPR applies to a transfer, we rely on the provider's standard contractual clauses or an adequacy decision. By using your own keys and connected apps you direct those transfers yourself.</p>
<h2>7. Retention</h2>
<p>Workspace content stays until you delete it (chats, notes, media and showcase entries can be deleted in the Service; missions can be voided or stopped; contact us to erase a whole workspace). Keys and tokens live only as long as the server process. Rate-limit counters last minutes. Server logs are kept for a short operational period. Backups, where taken, expire on a rolling basis.</p>
<h2>8. Your rights</h2>
<p>Under GDPR you can ask for access to, correction of, erasure of, or a copy (portability) of your personal data; object to or restrict processing; and withdraw consent at any time without affecting earlier processing. Under DPDP you have corresponding rights of access, correction, erasure, grievance redressal and nomination. You may also complain to your supervisory authority (in the EU, your national data protection authority; in the UK, the ICO; in India, the Data Protection Board). To exercise a right, use the support link in Get Help; we will answer within the time the law sets, normally one month. The Settings page lets you export your whole workspace at any time.</p>
<h2>9. Security</h2>
<p>We use TLS in transit, rate limits, an access code where enabled, memory-only keys and tokens, atomic writes for the ledger, and baseline security headers. No system is perfectly secure; if we learn of a breach affecting your data we will inform you and any authority as the law requires.</p>
<h2>10. Children</h2>
<p>The Service is for adults. We do not knowingly collect data from anyone under 18. If you believe a minor has used the Service, contact us and we will delete the data.</p>
<h2>11. Automated decisions</h2>
<p>The Service automates the running of missions and the checking of Outputs, but every decision with consequences for you (spending beyond a ceiling, accepting a risk, stopping a run) is taken by you, on the record. We do not make decisions producing legal or similarly significant effects about you by automated means.</p>
<h2>12. Changes and contact</h2>
<p>We will present material changes to this Policy for acceptance again with a new version date. Questions, requests and complaints go through the support link in Get Help.</p>
`;

const AI = `
<p><b>Read this before relying on anything the house produces.</b></p>
<h2>1. Outputs are machine-generated</h2>
<p>Artifacts, chat replies, panel positions, critiques, narratives, digests and record answers are produced by software. Where you load your own key, they come from the third-party AI model you selected. Where you do not, the substance is house-scripted sample material, and it is labelled as such in the artifact, on the tape and in the provenance block. Sample material, illustrative figures and placeholders are not statements of fact about you, your market, or anyone else.</p>
<h2>2. They can be wrong</h2>
<p>AI models make mistakes: they can misstate facts, invent figures, misread sources, omit what matters, reflect bias in their training data, and sound confident while doing it. The Service applies automated checks (validator lanes, a figure-tracing lane, adviser critique, a terminal review) and records what passed and what did not. Those checks reduce some classes of error; they do not guarantee accuracy, completeness, currency, or fitness for any purpose.</p>
<h2>3. Not professional advice</h2>
<p>Nothing the Service produces is legal, financial, investment, tax, medical, safety, engineering or other professional advice, and no professional relationship is created. Decisions with legal, financial, health, safety or similar consequences must be reviewed by a qualified professional before you act on them.</p>
<h2>4. You are responsible</h2>
<p>You are responsible for reviewing, verifying and, where needed, correcting every Output before you rely on it, share it, publish it, or present it as your own. Sources listed in a brief are pointers to verify, not verified citations, unless the record says a document was retrieved. Owner data you attach is parsed, not verified. Provenance shows how something was made; it does not make it true.</p>
<h2>5. Third-party models and their terms</h2>
<p>Calls made with your keys are subject to the model provider's terms, usage policies and pricing, and their content may be subject to their restrictions. You are responsible for compliance with them and for any charges.</p>
<h2>6. Disclosure</h2>
<p>Where the law, a platform, a client or an audience requires disclosure that content is AI-generated or AI-assisted, you are responsible for making it. The provenance block and audit bundle exist to help you do so honestly.</p>
<p>This Disclaimer forms part of the Terms and Conditions. If you do not accept it, do not use the Service.</p>
`;

export const LEGAL = {
  version: LEGAL_VERSION,
  docs: {
    terms: { id: 'terms', title: 'Terms and Conditions', html: TERMS },
    privacy: { id: 'privacy', title: 'Privacy and GDPR Policy', html: PRIVACY },
    ai: { id: 'ai', title: 'AI Disclaimer', html: AI },
  },
};

export function legalPage(id) {
  const d = LEGAL.docs[id];
  if (!d) return null;
  const nav = Object.values(LEGAL.docs).map((x) => `<a href="/legal/${x.id}"${x.id === id ? ' class="on"' : ''}>${x.title}</a>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${d.title} · Prajñā</title>
<style>body{margin:0;background:#f6f4ee;color:#14140f;font:16px/1.6 -apple-system,'Segoe UI',system-ui,sans-serif}.wrap{max-width:46rem;margin:0 auto;padding:3rem 1.5rem 5rem}nav{display:flex;gap:1rem;flex-wrap:wrap;font-size:.85rem;margin-bottom:2rem}nav a{color:#5a4a20;text-decoration:none;border-bottom:1px solid transparent}nav a.on{border-bottom-color:#8a4b13;color:#14140f;font-weight:700}h1{font-size:1.7rem;margin:0 0 .3rem}h2{font-size:1rem;margin:1.8rem 0 .4rem}.note{font-size:.8rem;color:#666}p,li{margin:.5rem 0}code{font-size:.85em}</style></head><body><div class="wrap">
<nav>${nav}<a href="/">Back to the workspace</a></nav>
<h1>${d.title}</h1><p class="note">Version ${LEGAL.version}. Prajñā, the Service.</p>
${d.html}
<p class="note">Terms and Conditions, Privacy and GDPR Policy and AI Disclaimer are accepted together when a workspace is opened; the acceptance is recorded with its version and time.</p>
</div></body></html>`;
}
